# Generated by Django 4.2.2 on 2024-09-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numeroDocumento',
            field=models.IntegerField(max_length=20, verbose_name='digite su número de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('REGISTRO CIVIL', 'Registro civil')], default='CC', max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
