# Generated by Django 4.2.2 on 2024-05-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numeroDocumento',
            field=models.IntegerField(default=False, verbose_name='Digite su numero de documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('REGISTRO CIVIL', 'Registro civil')], default=False, max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
