# Generated by Django 4.2.2 on 2024-09-28 04:43
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_numerodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numeroDocumento',
            field=models.BigIntegerField(unique=True, verbose_name='digite su número de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('RC', 'Registro civil')], default='PP', max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
