# Generated by Django 4.2.2 on 2024-09-27 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título de la encuesta')),
                ('tipoEncuesta', models.CharField(choices=[('Publica', 'Encuesta pública'), ('Privada', 'Encuesta privada')], default='Publica', max_length=50, verbose_name='Tipo de Encuesta')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField(null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPregunta', models.CharField(choices=[('1', 'Pregunta general'), ('2', 'Pregunta tipo sí o no'), ('3', 'Pregunta numérica'), ('4', 'Pregunta tipo selección múltiple')], max_length=30, verbose_name='Seleccione el tipo de pregunta')),
                ('texto_pregunta', models.CharField(max_length=200, verbose_name='Digite la pregunta')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuestaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('REGISTRO_CIVIL', 'Registro civil')], max_length=20, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=20, unique=True, verbose_name='Digite su número de documento')),
                ('nombre', models.CharField(max_length=50, verbose_name='Digite su nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_preguntas_publica', to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuestaPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_preguntas_privada', to='encuesta.encuesta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_encuesta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.CharField(max_length=200, verbose_name='Digite su respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta', to='encuesta.pregunta')),
                ('respuestaEncuestaPrivada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_encuesta_privada', to='encuesta.respuestaencuestaprivada')),
                ('respuestaEncuestaPublica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_encuesta_publica', to='encuesta.respuestaencuestapublica')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=100, verbose_name='Digite la opción')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='encuesta.pregunta')),
            ],
        ),
    ]
