# Generated by Django 4.2.2 on 2024-05-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo de la encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pre', models.CharField(max_length=200, verbose_name='Digite la pregunta general')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaNumerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pre', models.CharField(max_length=200, verbose_name='Digite la pregunta numérica')),
                ('rango', models.IntegerField(default=1, verbose_name='Rango mínimo 1 rango maximo 10')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaSelectMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pre', models.CharField(max_length=200, verbose_name='Digite la pregunta de selección multiple')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaSiONo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pre', models.CharField(max_length=200, verbose_name='Digite la pregunta de sí o no')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaSiONo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField(max_length=200, verbose_name='Seleccione Si o No')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta_siOno', to='encuesta.preguntasiono')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaSelectMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=200, verbose_name='Seleccione una opción')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta_selectMultiple', to='encuesta.preguntaselectmultiple')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaNumerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField(verbose_name='Digite un numero de respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta_numerica', to='encuesta.preguntanumerica')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=200, verbose_name='Digite su respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta_general', to='encuesta.preguntageneral')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('REGISTRO CIVIL', 'Registro civil')], max_length=20, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=12, verbose_name='Digite su numero de documento')),
                ('nombreUsuario', models.CharField(max_length=200, verbose_name='Digite su nombre')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_preguntas', to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPreguntaSelectMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=255, verbose_name='Opción')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.preguntaselectmultiple')),
            ],
        ),
    ]
