# Generated by Django 4.2.2 on 2024-09-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado de la encuesta'),
        ),
    ]
