# Generated by Django 4.2.2 on 2024-05-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.preguntageneral')),
                ('pregunta_numerica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.preguntanumerica')),
                ('pregunta_select_multiple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.preguntaselectmultiple')),
                ('pregunta_si_o_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.preguntasiono')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_respuestas', to='encuesta.respuesta')),
            ],
        ),
    ]
