# Generated by Django 4.2.2 on 2024-05-22 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuestaPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuestaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('REGISTRO CIVIL', 'Registro civil')], max_length=20, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.IntegerField(verbose_name='Digite su numero de documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Digite su nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipoEncuesta',
            field=models.CharField(choices=[('Publica', 'Encuesta pública'), ('Privada', 'Encuesta privada')], default=False, max_length=50, verbose_name='Tipo de Encuesta'),
        ),
        migrations.AlterField(
            model_name='preguntanumerica',
            name='rango',
            field=models.IntegerField(default=1, verbose_name='Rango de la encuesta: mínimo 1 rango, maximo 10'),
        ),
        migrations.DeleteModel(
            name='RespuestaEncuesta',
        ),
        migrations.AddField(
            model_name='respuestaencuestapublica',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_preguntas', to='encuesta.encuesta'),
        ),
        migrations.AddField(
            model_name='respuestaencuestaprivada',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_preguntas_privada', to='encuesta.encuesta'),
        ),
        migrations.AddField(
            model_name='respuestaencuestaprivada',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_encuesta', to=settings.AUTH_USER_MODEL),
        ),
    ]
