# Generated by Django 4.2.2 on 2024-05-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_respuestadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('REGISTRO CIVIL', 'Registro civil')], max_length=20, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=12, verbose_name='Digite su numero de documento')),
                ('nombreUsuario', models.CharField(max_length=200, verbose_name='Digite su nombre')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_preguntas', to='encuesta.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=200, verbose_name='Digite su respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta_general', to='encuesta.preguntageneral')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaNumerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField(max_length=200, verbose_name='Digite un numero de respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta_numerica', to='encuesta.preguntanumerica')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaSiONo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField(max_length=200, verbose_name='Seleccione Si o No')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta_siOno', to='encuesta.preguntasiono')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPreguntaSlectMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=200, verbose_name='Seleccione una opción')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta_selectMultiple', to='encuesta.preguntaselectmultiple')),
            ],
        ),
        migrations.RemoveField(
            model_name='respuestadetalle',
            name='pregunta_general',
        ),
        migrations.RemoveField(
            model_name='respuestadetalle',
            name='pregunta_numerica',
        ),
        migrations.RemoveField(
            model_name='respuestadetalle',
            name='pregunta_select_multiple',
        ),
        migrations.RemoveField(
            model_name='respuestadetalle',
            name='pregunta_si_o_no',
        ),
        migrations.RemoveField(
            model_name='respuestadetalle',
            name='respuesta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='RespuestaDetalle',
        ),
    ]
