# Generated by Django 4.2.2 on 2024-09-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_encuesta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='fechaModificacion',
            field=models.DateTimeField(null=True),
        ),
    ]
