# Generated by Django 4.2.2 on 2024-05-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_respuestaencuesta_respuestapreguntageneral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestapreguntanumerica',
            name='respuesta',
            field=models.IntegerField(verbose_name='Digite un numero de respuesta'),
        ),
    ]
