# Generated by Django 4.2.2 on 2024-05-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_alter_respuestapreguntanumerica_respuesta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RespuestaPreguntaSlectMultiple',
            new_name='RespuestaPreguntaSelectMultiple',
        ),
    ]
